### ISSUE TITLE
Unable to find package 'Ninject.WebContext'

### ISSUE THREAD

**Issue by GuillaumeSpera** [Vtek/Ninject.WebContext#1]
Hi Bro !

The Package Manager is unable to retrieve your package :(
I hope you'll fix it soon, I'm looking forward to be able to try your implementation !

![webcontext](https://cloud.githubusercontent.com/assets/7603330/6542477/a9ccc722-c4f9-11e4-9b9f-f4a811c87c6c.PNG)

Thank you :+1:

**Comment by Vtek** [comment]
Hi !

It's right, i forgot to push it on NuGet... :(

**Comment by Vtek** [comment]
Done !
